# Site settings
title: Duc Nguyen
# email: trungduc1992@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog documenting the winding journey to be good.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: none
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
